version: 2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.4
    parallelism: 2
    steps:
      - checkout
      - run: gem install bundler:2.5.17
      - run: bundle install
      - run:
          name: the tests
          command: |
            TESTFILES=$(cat testname-list.txt | circleci tests split --split-by=timings --timings-type=testname)
            #  TESTFILES=$(find spec -name '*_spec.rb' | circleci tests split --split-by=timings --timings-type=filename)
             bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml $TESTFILES
             
   #         circleci tests glob "./spec/**/*_spec.rb" | circleci tests run --command="xargs bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml" --verbose --split-by=timings 
      - store_test_results:
          path: ~/rspec 
      - store_artifacts: 
          path: ~/rspec 
